### ISSUE TITLE
authenticity token not being picked up

### ISSUE THREAD

**Issue by rurounijones** [jamesgolick/trample#4]
I have tried every single version of trample on the network but none of them are working in that when I try and login to my Rails 2.3.5 application the authenticity token is not being passed as one of the post parameters.

wgibbs and kyuusik both have the same problem even though they apparently have patches designed to deal with this. 

Any pointers?

**Comment by rurounijones** [comment]
After many hours looking at it, I realise I was messing up my login parameters.

:user_id and :user_password vs :user => {:code, :password}

**Comment by jamesgolick** [comment]
This issue is resolved, then?

**Comment by rurounijones** [comment]
This is resolved.
